name:                rush
version:             0.1.0.0
github:              "bobbygebert/rush"
license:             MIT
author:              "Bobby Gebert"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bobbygebert/rush#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - bytestring
  - containers
  - filepath
  - hspec
  - hspec-megaparsec
  - llvm-hs >= 9.0 && <= 9.1
  - llvm-hs-pure >= 9.0 && < 9.1
  - llvm-hs-pretty >= 0.9
  - megaparsec
  - mtl
  - parser-combinators
  - pretty
  - text

executables:
  rush-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - containers
    - filepath
    - optparse-applicative
    - rush
    - text

tests:
  rush-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - process
    - rush
    - temporary
    - text
